- name: "vault login"
  command: >-
    docker exec -e 'VAULT_ADDR={{ vault_api_addr }}' {{ vault_docker_name }}
    vault login {{ vault_token }}
  changed_when: false
  run_once: true
  become: true

- name: "Check Vault Issuing backend exists"
  command: >-
    docker exec  -e 'VAULT_ADDR={{ vault_api_addr }}' {{ vault_docker_name }}
    vault read {{ vault_intermediate_ca_name }}/cert/ca
  run_once: true
  register: issuing_backend_exists
  changed_when: false
  failed_when: "issuing_backend_exists.rc not in [ 0, 2 ]"

- name: "Issuing CA Backend"
  block:
    - name: "Copy Issuing bundle"
      copy:
        src: "/tmp/issuing-bundle.pem"
        dest: "~/issuing-bundle.pem"
        mode: '0400'
      become: true

    - name: "Enable PKI Intermediate Backend"
      command: >-
        docker exec -e 'VAULT_ADDR={{ vault_api_addr }}' {{ vault_docker_name }}
        vault secrets enable -path={{ vault_intermediate_ca_name }}
        -description="{{ vault_intermediate_ca_name }} CA v1" pki
      changed_when: false

    # 5 years
    - name: "Tune Issuing Backend"
      command: >-
        docker exec -e 'VAULT_ADDR={{ vault_api_addr }}' {{ vault_docker_name }}
        vault secrets tune -max-lease-ttl=43830h {{ vault_intermediate_ca_name }}
      changed_when: false

    - name: "Copy Issuing pem bundle"
      command: docker cp ~/issuing-bundle.pem {{ vault_docker_name }}:/
      changed_when: false
      become: true

    - name: "Delete Issuing Bundle"
      file:
        path: "~/issuing-bundle.pem"
        state: absent
      become: true

    - name: "Upload Issuing pem bundle"
      command: >-
        docker exec -e 'VAULT_ADDR={{ vault_api_addr }}' {{ vault_docker_name }}
        vault write {{ vault_intermediate_ca_name }}/config/ca pem_bundle=@/issuing-bundle.pem
        -format=json
      changed_when: false

    - name: "Delete Issuing Bundle in container"
      command: >-
        docker exec {{ vault_docker_name }}
        rm -f /issuing-bundle.pem
      changed_when: false
      become: true

    - name: "Create ServerCert role"
      command: >-
        docker exec -e "VAULT_ADDR={{ vault_api_addr }}" {{ vault_docker_name }}
        vault write {{ vault_intermediate_ca_name }}/roles/ServerCert
        max_ttl=8760h ttl=8760h
        allow_ip_sans=true require_cn=false server_flag=true
        key_type=rsa key_bits=4096
        country='NL' locality='Groningen' organization='RUG' ou='HPC'
      changed_when: false
  run_once: true
  when: issuing_backend_exists.rc == 2

- name: "vault logout"
  command: >-
    docker exec {{ vault_docker_name }}
    rm -f ~/.vault-token
  changed_when: false
  run_once: true
  become: true
