namespace: stackhpc
name: hashicorp
description: >
  Hashicorp Vault/Consul deployment and configuration
version: "2.5.0"
readme: "README.md"
authors:
  - "Michał Nasiadka"
dependencies:
  "community.docker": "*"
license:
  - "Apache-2.0"
tags:
  - consul
  - hashicorp
  - infrastructure
  - security
  - vault
repository: "https://github.com/stackhpc/ansible-collection-hashicorp"
