namespace: stackhpc
name: hashicorp
description: >
  Hashicorp Vault/Consul deployment and configuration
version: "2.6.1"
readme: "README.md"
authors:
  - "Michał Nasiadka"
  - "Mark Goddard"
  - "Matt Anson"
  - "Pierre Riteau"
  - "Bartosz Bezak"
  - "Kyle Dean"
  - "Jack Hodgkiss"
dependencies:
  "community.docker": "*"
license:
  - "Apache-2.0"
tags:
  - consul
  - hashicorp
  - infrastructure
  - security
  - vault
  - openbao
repository: "https://github.com/stackhpc/ansible-collection-hashicorp"
