namespace: "stackhpc"
name: "hashicorp"
version: "2.3.0"
readme: "README.md"
authors:
  - "Michał Nasiadka"
dependencies:
  "community.docker": "*"
license:
  - "Apache-2.0"
tags:
  - hashicorp
  - vault
  - consul
repository: "https://github.com/stackhpc/ansible-collection-hashicorp"
