---
vault_pki_root_create: true
vault_pki_root_ca_name: ""
vault_pki_root_ca_common_name: "{{ vault_pki_root_ca_name }}"
vault_pki_write_root_ca_to_file: false

vault_pki_intermediate_create: true
vault_pki_intermediate_import: false
vault_pki_intermediate_export: false
vault_pki_intermediate_ca_name: ""
vault_pki_intermediate_ca_common_name: "{{ vault_pki_intermediate_ca_name }}"
vault_pki_intermediate_ca_bundle: ""

vault_pki_intermediate_roles: {}

vault_pki_generate_certificates: false

vault_pki_write_certificates_host: "localhost"
vault_pki_write_certificates_directory: ""
vault_pki_write_certificate_files: false

vault_pki_certificate_subject: []
