---
- name: "Check if Cert already exists"
  stat:
    path: "{{ vault_pki_write_certificates_directory }}/{{ item.common_name | replace(' ', '-') }}.pem"
  register: cert_file
  loop: "{{ vault_pki_certificate_subject }}"

- name: Print cert_file
  debug:
    var: cert_file

- name: "Generate Certificate"
  hashivault_pki_cert_issue:
    url: "{{ vault_api_addr }}"
    token: "{{ vault_token }}"
    ca_cert: "{{ vault_ca_cert | default(omit) }}"
    mount_point: "{{ vault_pki_intermediate_ca_name }}"
    common_name: "{{ item.common_name }}"
    role: "{{ item.role }}"
    extra_params: "{{ item.extra_params }}"
  loop: "{{ vault_pki_certificate_subject }}"
  register: certificate_data
  when:
    - not cert_file.stat.exists or vault_pki_overwrite_certificates | bool

- name: "Write out certificate pem_bundle"
  vars:
    cert_name: "{{ item.item.common_name if item.item.common_name | length > 0 else item.item.extra_params.ip_sans }}"
  copy:
    content: |
      {{ item.data.certificate }}
      {{ item.data.issuing_ca }}
      {{ item.data.private_key }}
    dest: "{{ vault_pki_write_certificates_directory }}/{{ cert_name | replace(' ', '-') }}.pem"
    mode: 0600
  delegate_to: "{{ vault_pki_write_certificates_host }}"
  loop: "{{ certificate_data.results }}"
  when:
    - vault_pki_write_pem_bundle | bool
    - vault_pki_write_certificate_files | bool
    - not cert_file.stat.exists or vault_pki_overwrite_certificates | bool


- name: "Write out certificate"
  vars:
    cert_name: "{{ item.item.common_name if item.item.common_name | length > 0 else item.item.extra_params.ip_sans }}"
  copy:
    content: |
      {{ item.data.certificate }}
      {{ item.data.issuing_ca }}
    dest: "{{ vault_pki_write_certificates_directory }}/{{ cert_name | replace(' ', '-') }}.pem"
    mode: 0600
  delegate_to: "{{ vault_pki_write_certificates_host }}"
  loop: "{{ certificate_data.results }}"
  when:
    - not vault_pki_write_pem_bundle | bool
    - vault_pki_write_certificate_files | bool
    - not cert_file.stat.exists or vault_pki_overwrite_certificates | bool


- name: "Write out key"
  vars:
    cert_name: "{{ item.item.common_name if item.item.common_name | length > 0 else item.item.extra_params.ip_sans }}"
  copy:
    content: |
      {{ item.data.private_key }}
    dest: "{{ vault_pki_write_certificates_directory }}/{{ cert_name | replace(' ', '-') }}-key.pem"
    mode: 0600
  delegate_to: "{{ vault_pki_write_certificates_host }}"
  loop: "{{ certificate_data.results }}"
  when:
    - not vault_pki_write_pem_bundle | bool
    - vault_pki_write_certificate_files | bool
    - not cert_file.stat.exists or vault_pki_overwrite_certificates | bool
