---
- name: "Check if Cert already exists in certificates directory"
  stat:
    path: "{{ vault_pki_certificates_directory }}/{{ item.common_name | replace(' ', '-') }}.crt"
  register: cert_stat_file
  delegate_to: "{{ vault_pki_write_certificates_host }}"
  loop: "{{ vault_pki_certificate_subject }}"
  loop_control:
    label: "{{ item.common_name }}"
  when: vault_pki_write_certificate_files | bool

- name: "Generate Certificate"
  hashivault_pki_cert_issue:
    url: "{{ vault_api_addr }}"
    token: "{{ vault_token }}"
    ca_cert: "{{ vault_ca_cert | default(omit) }}"
    mount_point: "{{ vault_pki_intermediate_ca_name }}"
    common_name: "{{ item.common_name }}"
    role: "{{ item.role }}"
    extra_params: "{{ item.extra_params }}"
  loop: "{{ vault_pki_certificate_subject }}"
  loop_control:
    label: "{{ item.common_name }}"
  register: cert_data

- name: "Write out certificate pem_bundle"
  vars:
    cert_name: "{{ item.item.common_name if item.item.common_name | default() | length > 0 else item.item.extra_params.ip_sans | default() }}"
    cert_file: "{{ cert_stat_file.results | selectattr('item.common_name', 'match', item.item.common_name) | first }}"
  copy:
    content: |
      {{ item.data.certificate }}
      {{ item.data.issuing_ca }}
      {{ item.data.private_key }}
    dest: "{{ vault_pki_certificates_directory }}/{{ cert_name | replace(' ', '-') }}.pem"
    mode: "0600"
  delegate_to: "{{ vault_pki_write_certificates_host }}"
  loop: "{{ cert_data.results }}"
  loop_control:
    label: "{{ cert_name | default() }}"
  when:
    - vault_pki_write_pem_bundle | bool
    - vault_pki_write_certificate_files | bool
    - not cert_file.stat.exists or vault_pki_overwrite_certificates | bool

- name: "Write out certificate"
  vars:
    cert_name: "{{ item.item.common_name if item.item.common_name | default() | length > 0 else item.item.extra_params.ip_sans | default() }}"
    cert_file: "{{ cert_stat_file.results | selectattr('item.common_name', 'match', item.item.common_name) | first }}"
  copy:
    content: |
      {{ item.data.certificate }}
      {{ item.data.issuing_ca }}
    dest: "{{ vault_pki_certificates_directory }}/{{ cert_name | replace(' ', '-') }}.crt"
    mode: "0600"
  delegate_to: "{{ vault_pki_write_certificates_host }}"
  loop: "{{ cert_data.results }}"
  loop_control:
    label: "{{ cert_name | default() }}"
  when:
    - not vault_pki_write_pem_bundle | bool
    - vault_pki_write_certificate_files | bool
    - not cert_file.stat.exists or vault_pki_overwrite_certificates | bool

- name: "Write out key"
  vars:
    cert_name: "{{ item.item.common_name if item.item.common_name | default() | length > 0 else item.item.extra_params.ip_sans | default() }}"
    cert_file: "{{ cert_stat_file.results | selectattr('item.common_name', 'match', item.item.common_name) | first }}"
  copy:
    content: |
      {{ item.data.private_key }}
    dest: "{{ vault_pki_certificates_directory }}/{{ cert_name | replace(' ', '-') }}.key"
    mode: "0600"
  delegate_to: "{{ vault_pki_write_certificates_host }}"
  loop: "{{ cert_data.results }}"
  loop_control:
    label: "{{ cert_name | default() }}"
  when:
    - not vault_pki_write_pem_bundle | bool
    - vault_pki_write_certificate_files | bool
    - not cert_file.stat.exists or vault_pki_overwrite_certificates | bool
