---
# HA migration of Vault to OpenBao
# Generally following the upstream docs: https://github.com/openbao/openbao/pull/1155
# At time of writing the above PR hasn't merged but might be soon

# Ensure backup exists
# Find the leader
# Loop through non-leader nodes
# Stop Vault, Start OpenBao in its place
# Join the existing cluster
# Unseal if sealed
# Ensure it joins the cluster and has become a voter
# Repeat for all non-leader nodes
# Force leader to step down
# Make sure a new leader is elected
# Run rejoin on former leader node

- name: Ensure Raft Snapshot exists
  ansible.builtin.stat:
    path: "{{ vault_staging_dir_path }}/raft-snapshot.snap"
  register: raft_snapshot_status
  failed_when: not raft_snapshot_status.stat.exists
  changed_when: false
  when: inventory_hostname == vault_raft_leader

- name: Set vault_all list
  ansible.builtin.set_fact:
    vault_all: "{{ vault_raft_followers + [vault_raft_leader] }}"

- name: Ensure the leader is the last item of vault_all
  ansible.builtin.assert:
    that:
      - vault_all | last == vault_raft_leader

- name: show vault_all
  debug:
    var: vault_all

- name: Migrate the cluster to OpenBao one-by-one
  include_tasks: openbao.yml
  loop: "{{ vault_all }}"
  loop_control:
    loop_var: vault_host
  run_once: true
