---
- name: Show which host is currently worked on
  debug:
    msg: "Current host: {{ item }}"

- name: Step down from leader is current host is a Raft leader
  when: item == _vault_leader
  block:
    - name: Step down from leader if current host is Vault Raft leader
      community.docker.docker_container_exec:
        command: |
          vault operator step-down
        container: "{{ migration_vault_docker_name }}"
        env:
          VAULT_ADDR: "{{ migration_common_api_addr }}"
          VAULT_TOKEN: "{{ migration_common_root_token }}"
          VAULT_CAPATH: "{{ '/vault/config/' + migration_common_tls_ca if migration_common_tls_ca != '' else omit }}"
        user: root
      delegate_to: "{{ item }}"
      vars:
        ansible_host: "{{ hostvars[item].ansible_host }}"

    - name: Wait for the cluster to set a new leader
      ansible.builtin.wait_for:
        timeout: 10

    - name: Get new leader API address from OpenBao running host
      ansible.builtin.uri:
        url: "http://127.0.0.1:8200/v1/sys/leader"
      register: new_leader_api_addr_query
      delegate_to: "{{ groups['ordered_vault_hosts'][0] }}"
      vars:
        ansible_host: "{{ hostvars[groups['ordered_vault_hosts'][0]].ansible_host }}"

    - name: Show new leader
      debug:
        var: new_leader_api_addr_query.json
      run_once: true

- name: Stop Vault container at current host
  community.docker.docker_container:
    name: "{{ migration_vault_docker_name }}"
    state: stopped
  become: true
  delegate_to: "{{ item }}"
  vars:
    ansible_host: "{{ hostvars[item].ansible_host }}"

- name: Apply OpenBao role for current host
  ansible.builtin.include_role:
    name: stackhpc.hashicorp.openbao
    apply:
      delegate_to: "{{ item }}"
      vars:
        ansible_host: "{{ hostvars[item].ansible_host }}"
        openbao_docker_name: "{{ migration_openbao_docker_name }}"
        openbao_bind_addr: "{{ migration_common_bind_addr }}"
        openbao_api_addr: "{{ hostvars[item].migration_common_api_addr }}"
        openbao_registry_url: "{{ migration_openbao_registry_url }}"
        openbao_registry_username: "{{ migration_openbao_registry_username }}"
        openbao_registry_password: "{{ migration_openbao_registry_password }}"
        openbao_config_dir: "{{ migration_openbao_config_dir }}"
        openbao_cluster_name: "{{ migration_common_cluster_name }}"
        openbao_docker_image: "{{ migration_openbao_docker_image }}"
        openbao_docker_tag: "{{ migration_openbao_docker_tag }}"
        openbao_tls_cert: "{{ migration_common_tls_cert }}"
        openbao_tls_key: "{{ migration_common_tls_key }}"
        openbao_tls_ca: "{{ migration_common_tls_ca }}"
        openbao_raft_leaders:
          - "{{ (new_leader_api_addr_query.json.leader_address if item == _vault_leader else _vault_leader_api_addr) | urlsplit('hostname') }}"

- name: Unseal OpenBao at current host
  ansible.builtin.include_role:
    name: stackhpc.hashicorp.vault_unseal
    apply:
      delegate_to: "{{ item }}"
      vars:
        ansible_host: "{{ hostvars[item].ansible_host }}"
        vault_api_addr: "{{ hostvars[item].migration_common_api_addr }}"
        vault_unseal_keys: "{{ migration_common_unseal_keys }}"
