---
- name: "Vault Prerequisites"
  ansible.builtin.import_tasks: prereqs.yml

# - name: "Migrate storage to Raft"
#   ansible.builtin.import_tasks: raft.yml

# - name: "Single Node Migration"
#   ansible.builtin.import_tasks: single_node_migration.yml
#   when: _vault_followers | length == 0

- name: "Prerequsites for HA clustered OpenBao migration"
  ansible.builtin.include_tasks: ha_prereqs.yml
  when: _vault_followers | length > 0

# - name: "HA cluster migration"
#   ansible.builtin.include_tasks: ha_migration.yml
#   loop: "{{ groups['ordered_vault_hosts'] }}"
#   run_once: true

- name: "Test"
  ansible.builtin.include_tasks: test.yml
  loop: "{{ groups['ordered_vault_hosts'] }}"
  run_once: true
