---
- name: Log into Docker registry
  docker_login:
    registry: "{{ migration_openbao_registry_url }}"
    username: "{{ migration_openbao_registry_username }}"
    password: "{{ migration_openbao_registry_password }}"
  when: migration_openbao_registry_username | length > 0
  become: true

- name: Get information of the Vault
  ansible.builtin.uri:
    url: "http://127.0.0.1:8200/v1/sys/ha-status"
    headers:
      X-Vault-Token: "{{ migration_common_root_token }}"
  run_once: true
  register: ha_status_query
  when: _vault_leader is undefined or _vault_leader == ""

- name: Set Vault leader as fact
  ansible.builtin.set_fact:
    _vault_leader: "{{ (ha_status_query.json.nodes | selectattr('active_node', 'equalto', true) | first).hostname }}"
    _vault_leader_api_addr: "{{ (ha_status_query.json.nodes | selectattr('active_node', 'equalto', true) | first).api_address }}"
  when: _vault_leader is undefined or _vault_leader == ""

- name: Set Vault followers as fact
  ansible.builtin.set_fact:
    _vault_followers: "{{ ha_status_query.json.nodes | selectattr('active_node', 'equalto', false) | map(attribute='hostname') | list }}"
  when: _vault_followers | length == 0

- name: Get Vault user id and group id
  community.docker.docker_container:
    name: "vault_uid_check"
    image: "{{ migration_vault_docker_image }}:{{ migration_vault_docker_tag }}"
    command: "id vault"
    detach: false
    cleanup: true
  register: id_vault_result
  become: true
  run_once: true

- name: Set Vault user id and group id
  ansible.builtin.set_fact:
    vault_uid: "{{ id_vault_result.container.Output | regex_search('uid=(\\d+)', '\\1') | first }}"
    vault_gid: "{{ id_vault_result.container.Output | regex_search('gid=(\\d+)', '\\1') | first }}"

- name: Get OpenBao user id and group id
  community.docker.docker_container:
    name: "openbao_uid_check"
    image: "{{ migration_openbao_docker_image }}:{{ migration_openbao_docker_tag }}"
    command: "id openbao"
    detach: false
    cleanup: true
  register: id_openbao_result
  become: true
  run_once: true

- name: Set OpenBao user id and group id
  ansible.builtin.set_fact:
    openbao_uid: "{{ id_openbao_result.container.Output | regex_search('uid=(\\d+)', '\\1') | first }}"
    openbao_gid: "{{ id_openbao_result.container.Output | regex_search('gid=(\\d+)', '\\1') | first }}"
