---
- name: Fail if the current storage backend is not Raft
  ansible.builtin.uri:
    url: "{{ migration_common_api_addr }}/v1/sys/seal-status"
  register: storage_query
  failed_when: storage_query.json.storage_type != "raft"
  changed_when: false
  run_once: true

- name: Backup snapshot of Raft data
  community.docker.docker_container_exec:
    command: |
      vault operator raft snapshot save raft-snapshot.snap
    container: "{{ migration_vault_docker_name }}"
    env:
      VAULT_ADDR: "{{ migration_common_api_addr }}"
      VAULT_TOKEN: "{{ migration_common_root_token }}"
      VAULT_CAPATH: "{{ '/vault/config/' + migration_common_tls_ca if migration_common_tls_ca != '' else omit }}"
    user: root
  become: true

- name: Copy Raft snapshot to host
  # NOTE: No module to copy from container to host, so using command
  ansible.builtin.command:
    cmd: "docker cp {{ migration_vault_docker_name }}:/raft-snapshot.snap {{ migration_vault_staging_dir_path }}"
  become: true
  changed_when: false
