---
- name: test A
  ansible.builtin.command:
    cmd: hostname
  register: test_a

- name: show test A result
  debug:
    var: test_a

- name: test B
  ansible.builtin.file:
    state: touch
    path: "~/{{ item }}.txt"

- name: test C
  ansible.builtin.command:
    cmd: hostname
  register: test_c
  delegate_to: "{{ item }}"
  vars:
    ansible_host: "{{ hostvars[item].ansible_host }}"

- name: show test C result
  debug:
    var: test_c

- name: test D
  ansible.builtin.file:
    state: touch
    path: "~/{{ item }}.conf"
  delegate_to: "{{ item }}"
  vars:
    ansible_host: "{{ hostvars[item].ansible_host }}"
