---
- name: Prerequesites
  hosts: "{{ vault_hosts }}"
  tasks:
    - name: Assert that length of vault_hosts is greater than 1
      ansible.builtin.assert:
        that: vault_hosts | length > 1

    - name: Find Vault leader
      ansible.builtin.shell:
        cmd: >
          docker exec -e VAULT_TOKEN=$VAULT_TOKEN -e VAULT_ADDR=$VAULT_ADDR
          {% if vault_tls_ca != "" %} -e VAULT_CAPATH=$VAULT_CAPATH {% endif %}
          {{ vault_docker_name }}
          vault operator members -format=json | jq -r '.Nodes[] | select(.active_node) | .hostname'
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
        VAULT_TOKEN: "{{ vault_root_token }}"
        VAULT_CAPATH: "{{ '/vault/config/' + vault_tls_ca if vault_tls_ca != '' else omit }}"
      register: vault_raft_leader_query
      changed_when: false
      when: vault_raft_leader is undefined or vault_raft_leader == ""

    - name: Set Vault leader
      ansible.builtin.set_fact:
        vault_raft_leader: "{{ vault_raft_leader_query.stdout }}"
      when: vault_raft_leader is undefined or vault_raft_leader == ""

    - name: Get leader API address
      ansible.builtin.shell:
        cmd: >
          docker exec -e VAULT_TOKEN=$VAULT_TOKEN -e VAULT_ADDR=$VAULT_ADDR
          {% if vault_tls_ca != "" %} -e VAULT_CAPATH=$VAULT_CAPATH {% endif %}
          {{ vault_docker_name }}
          vault status -format=json | jq -r '.leader_address'
      register: vault_leader_api_addr_query
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
        VAULT_TOKEN: "{{ vault_root_token }}"
        VAULT_CAPATH: "{{ '/vault/config/' + vault_tls_ca if vault_tls_ca != '' else omit }}"
      changed_when: false
      when: vault_leader_api_addr is undefined or vault_leader_api_addr == ""

    - name: Set fact the leader API address
      ansible.builtin.set_fact:
        vault_leader_api_addr: "{{ vault_leader_api_addr_query.stdout }}"
      when: vault_leader_api_addr is undefined or vault_leader_api_addr == ""

    - name: Create a new inventory group with Vault leader being last
      block:
        - name: Add Vault followers to the new inventory group
          ansible.builtin.add_host:
            name: "{{ item }}"
            groups: ordered_vault_hosts
          loop: "{{ vault_hosts }}"
          when: item != vault_raft_leader

        - name: Add Vault leader last
          ansible.builtin.add_host:
            name: "{{ vault_raft_leader }}"
            groups: ordered_vault_hosts

    - name: Copy TLS certificates from Vault to OpenBao
      block:
        - name: Copy TLS key
          ansible.builtin.copy:
            src: "{{ vault_config_dir }}/{{ vault_tls_key }}"
            dest: "{{ openbao_config_dir }}/{{ openbao_tls_key | default(vault_tls_key) }}"
            remote_src: true
        - name: Copy TLS certificate
          ansible.builtin.copy:
            src: "{{ vault_config_dir }}/{{ vault_tls_cert }}"
            dest: "{{ openbao_config_dir }}/{{ openbao_tls_cert | default(vault_tls_cert) }}"
            remote_src: true
      when: vault_tls_key and vault_tls_cert
      become: true

    - name: Copy CA from Vault to OpenBao
      ansible.builtin.copy:
        src: "{{ vault_config_dir }}/{{ vault_tls_ca }}"
        dest: "{{ openbao_config_dir }}/{{ openbao_tls_ca | default(vault_tls_ca) }}"
        remote_src: true
      when: vault_tls_ca
      become: true

- name: HA Vault to OpenBao migration except for leader
  hosts: ordered_vault_hosts
  serial: 1
  any_errors_fatal: true
  vars:
    vault_docker_name: vault
    openbao_docker_name: openbao
    vault_staging_dir_path: /var/lib/vault-migration
  tasks:
    - name: Step down from leader is current host is a Raft leader
      block:
        - name: Step down from leader if current host is Vault Raft leader
          community.docker.docker_container_exec:
            command: |
              vault operator step-down
            container: "{{ vault_docker_name }}"
            env:
              VAULT_ADDR: "{{ vault_api_addr }}"
              VAULT_TOKEN: "{{ vault_root_token }}"
              VAULT_CAPATH: "{{ '/vault/config/' + vault_tls_ca if vault_tls_ca != '' else omit }}"
            user: root

        - name: Wait for the cluster to set a new leader
          ansible.builtin.wait_for:
            timeout: 10

        - name: Get new leader API address from OpenBao running host
          ansible.builtin.uri:
            url: "http://127.0.0.1:8200/v1/sys/leader"
          register: new_leader_api_addr_query
          delegate_to: "{{ groups['ordered_vault_hosts'][0] }}"
          vars:
            ansible_host: "{{ hostvars[groups['ordered_vault_hosts'][0]].ansible_host }}"

        - name: Show new leader
          debug:
            var: new_leader_api_addr_query.json

      when: inventory_hostname == vault_raft_leader

    - name: Stop Vault container at current host
      community.docker.docker_container:
        name: "{{ vault_docker_name }}"
        state: stopped
      become: true

    - name: Apply OpenBao role for current host
      ansible.builtin.include_role:
        name: stackhpc.hashicorp.openbao
      vars:
        openbao_write_keys_file: false
        openbao_set_keys_fact: true
        openbao_raft_leaders:
          - "{{ (new_leader_api_addr_query.json.leader_address if inventory_hostname == vault_raft_leader else vault_leader_api_addr) | urlsplit('hostname') }}"

    # - name: Unseal OpenBao at current host with temporary keys
    #   ansible.builtin.include_role:
    #     name: stackhpc.hashicorp.vault_unseal
    #   vars:
    #     vault_api_addr: "{{ openbao_api_addr }}"
    #     vault_unseal_keys: "{{ openbao_keys.keys_base64 }}"

    - name: Unseal OpenBao at current host
      ansible.builtin.include_role:
        name: stackhpc.hashicorp.vault_unseal
      vars:
        vault_api_addr: "{{ openbao_api_addr }}"

    # - name: Copy migration file into Vault container at current host
    #   community.docker.docker_container_copy_into:
    #     container: "{{ openbao_docker_name }}"
    #     path: "{{ vault_staging_dir_path }}/raft-snapshot.snap"
    #     container_path: "/raft-snapshot.snap"
    #     # openbao user and group IDs
    #     owner_id: 100
    #     group_id: 1000
    #   become: true

    # - name: Restore Raft snapshot into OpenBao at current host
    #   community.docker.docker_container_exec:
    #     command: "vault operator raft snapshot restore -force /raft-snapshot.snap"
    #     container: "{{ openbao_docker_name }}"
    #     env:
    #       VAULT_ADDR: "{{ openbao_api_addr }}"
    #       VAULT_TOKEN: "{{ openbao_keys.root_token }}"
    #       VAULT_CAPATH: "{{ '/vault/config/' + vault_tls_ca if vault_tls_ca != '' else omit }}"
    #     user: openbao

    # - name: Check if OpenBao is initialized at current host
    #   uri:
    #     url: "{{ openbao_init_addr }}/v1/sys/init"
    #   register: openbao_init_status
    #   retries: 50
    #   delay: 1
    #   run_once: true
    #   until:
    #     - openbao_init_status.status == 200
    #     - openbao_init_status.json.initialized

    # - name: Wait for OpenBao to finish keyring swap at current host
    #   ansible.builtin.wait_for:
    #     timeout: 10

    # - name: Join cluster (current host)
    #   community.docker.docker_container_exec:
    #     command: "bao operator raft join {{ new_leader_api_addr if inventory_hostname == vault_raft_leader else vault_leader_api_addr }}"
    #     container: "{{ openbao_docker_name }}"
    #     env:
    #       VAULT_ADDR: "{{ openbao_api_addr }}"
    #       VAULT_TOKEN: "{{ openbao_keys.root_token }}"
    #       VAULT_CAPATH: "{{ '/vault/config/' + vault_tls_ca if vault_tls_ca != '' else omit }}"
    #     user: openbao

    # - name: Unseal OpenBao at current host
    #   ansible.builtin.include_role:
    #     name: stackhpc.hashicorp.vault_unseal
    #   vars:
    #     vault_api_addr: "{{ openbao_api_addr }}"
