---
- name: Prerequesites
  hosts: "{{ vault_hosts }}"
  tasks:
    - name: Assert that length of vault_hosts is greater than 1
      ansible.builtin.assert:
        that: vault_hosts | length > 1

    - name: Run vault_bao_migration prerequesites
      ansible.builtin.include_role:
        name: vault_bao_migration
        tasks_from: prereqs

    - name: Create a new inventory group with Vault leader being last
      block:
        - name: Add Vault followers to the new inventory group
          ansible.builtin.add_host:
            name: "{{ item }}"
            groups: ordered_vault_hosts
          loop: "{{ _vault_followers }}"

        - name: Add Vault leader last
          ansible.builtin.add_host:
            name: "{{ _vault_leader }}"
            groups: ordered_vault_hosts

    - name: Copy TLS certificates from Vault to OpenBao
      block:
        - name: Copy TLS key
          ansible.builtin.copy:
            src: "{{ migration_vault_config_dir }}/{{ migration_common_tls_key }}"
            dest: "{{ migration_openbao_config_dir }}/{{ migration_common_tls_key }}"
            remote_src: true
            # openbao user and group IDs
            owner: 100
            group: 1000
        - name: Copy TLS certificate
          ansible.builtin.copy:
            src: "{{ migration_vault_config_dir }}/{{ migration_common_tls_cert }}"
            dest: "{{ migration_openbao_config_dir }}/{{ migration_common_tls_cert }}"
            remote_src: true
            # openbao user and group IDs
            owner: 100
            group: 1000
      when: migration_common_tls_key and migration_common_tls_cert
      become: true

    - name: Copy CA from Vault to OpenBao
      ansible.builtin.copy:
        src: "{{ migration_vault_config_dir }}/{{ migration_common_tls_ca }}"
        dest: "{{ migration_openbao_config_dir }}/{{ migration_common_tls_ca }}"
        remote_src: true
        # openbao user and group IDs
        owner: 100
        group: 1000
      when: migration_common_tls_ca
      become: true

- name: HA Vault to OpenBao migration
  hosts: ordered_vault_hosts
  serial: 1
  any_errors_fatal: true
  vars:
    migration_vault_docker_name: vault
    migration_openbao_docker_name: openbao
    migration_vault_staging_dir_path: /var/lib/vault-migration
  tasks:
    - name: Step down from leader is current host is a Raft leader
      block:
        - name: Step down from leader if current host is Vault Raft leader
          community.docker.docker_container_exec:
            command: |
              vault operator step-down
            container: "{{ migration_vault_docker_name }}"
            env:
              VAULT_ADDR: "{{ migration_common_api_addr }}"
              VAULT_TOKEN: "{{ migration_common_root_token }}"
              VAULT_CAPATH: "{{ '/vault/config/' + migration_common_tls_ca if migration_common_tls_ca != '' else omit }}"
            user: root

        - name: Wait for the cluster to set a new leader
          ansible.builtin.wait_for:
            timeout: 10

        - name: Get new leader API address from OpenBao running host
          ansible.builtin.uri:
            url: "http://127.0.0.1:8200/v1/sys/leader"
          register: new_leader_api_addr_query
          delegate_to: "{{ groups['ordered_vault_hosts'][0] }}"
          vars:
            ansible_host: "{{ hostvars[groups['ordered_vault_hosts'][0]].ansible_host }}"

        - name: Show new leader
          debug:
            var: new_leader_api_addr_query.json

      when: inventory_hostname == _vault_leader

    - name: Stop Vault container at current host
      community.docker.docker_container:
        name: "{{ migration_vault_docker_name }}"
        state: stopped
      become: true

    - name: Apply OpenBao role for current host
      ansible.builtin.include_role:
        name: stackhpc.hashicorp.openbao
      vars:
        openbao_docker_name: "{{ migration_openbao_docker_name }}"
        openbao_bind_addr: "{{ secret_store_bind_address }}"
        openbao_api_addr: "{{ migration_common_api_addr }}"
        openbao_registry_url: "{{ migration_openbao_registry_url }}"
        openbao_registry_username: "{{ migration_openbao_registry_username }}"
        openbao_registry_password: "{{ migration_openbao_registry_password }}"
        openbao_config_dir: "{{ migration_openbao_config_dir }}"
        openbao_cluster_name: "{{ migration_common_cluster_name }}"
        openbao_docker_image: "{{ migration_openbao_docker_image }}"
        openbao_docker_tag: "{{ migration_openbao_docker_tag }}"
        openbao_tls_cert: "{{ migration_common_tls_cert }}"
        openbao_tls_key: "{{ migration_common_tls_key }}"
        openbao_tls_ca: "{{ migration_common_tls_ca }}"
        openbao_raft_leaders:
          - "{{ (new_leader_api_addr_query.json.leader_address if inventory_hostname == _vault_leader else _vault_leader_api_addr) | urlsplit('hostname') }}"

    - name: Unseal OpenBao at current host
      ansible.builtin.include_role:
        name: stackhpc.hashicorp.vault_unseal
      vars:
        vault_api_addr: "{{ migration_common_api_addr }}"
        vault_unseal_keys: "{{ migration_common_unseal_keys }}"
