---
- name: Hashicorp Vault to OpenBao migration
  gather_facts: true
  hosts: "{{ groups[vault_hosts_group] | default([]) }}"
  vars:
    vault_hosts_group: ""
  tasks:
    - name: Prerequesites
      ansible.builtin.include_role:
        name: vault_bao_migration
        tasks_from: prereqs

    - name: Get current storage backend
      ansible.builtin.uri:
        url: "{{ migration_common_api_addr }}/v1/sys/seal-status"
      run_once: true
      register: storage_query
      retries: 50
      delay: 1
      until:
        - storage_query.status == 200
        - storage_query.json.storage_type is defined

    - name: Backup Consul
      ansible.builtin.include_role:
        name: vault_bao_migration
        tasks_from: consul_backup
      when: storage_query.json.storage_type != "raft"

    - name: Migrate storage to Raft
      ansible.builtin.include_role:
        name: vault_bao_migration
        tasks_from: raft
      when: storage_query.json.storage_type != "raft"

    - name: Backup Raft
      ansible.builtin.include_role:
        name: vault_bao_migration
        tasks_from: raft_backup

    - name: Single Node Migration
      ansible.builtin.include_role:
        name: vault_bao_migration
        tasks_from: single_node_migration
      when: _vault_followers | length == 0

    - name: HA migration prerequesites
      ansible.builtin.include_role:
        name: vault_bao_migration
        tasks_from: ha_prereqs
      when: _vault_followers | length > 0

- name: HA cluster migration
  ansible.builtin.import_playbook: ha_migration.yml
  when: _vault_followers | length > 0
