# Default volume mapping
_vault_default_volumes:
  - "{{ vault_config_dir }}:/vault/config"
_consul_default_volumes:
  - "{{ consul_docker_volume }}:/consul/data"

# Exposed for playbooks to access later
vault_extra_volumes: []
consul_extra_volumes: []

# Combined volume lists
_vault_volumes: "{{ _vault_default_volumes + vault_extra_volumes }}"
_consul_volumes: "{{ _consul_default_volumes + consul_extra_volumes }}"

